# Generated by Django 4.2.5 on 2023-09-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ad_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='description2',
            field=models.TextField(blank=True),
        ),
    ]
