# Generated by Django 4.2.5 on 2023-09-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_ad_description2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='media')),
                ('description', models.TextField()),
                ('position', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
