# Generated by Django 4.2.5 on 2023-10-01 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_blogcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
