# Generated by Django 4.2.5 on 2023-10-07 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_productreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='email',
        ),
    ]
