# Generated by Django 4.2.5 on 2023-10-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_blogreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogreview',
            name='slug',
        ),
        migrations.AlterField(
            model_name='blogreview',
            name='id',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
