# Generated by Django 4.2.5 on 2023-10-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_blogreview_slug_alter_blogreview_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=200)),
                ('Lastname', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=400)),
                ('phone', models.CharField(max_length=100)),
                ('note', models.TextField()),
            ],
        ),
    ]
